# This action updates the packages.elecord.app site.
# It adds new redirects and replaces relevant files.

on:
    workflow_call:
        secrets:
            ELECORD_DESKTOP_TOKEN:
                required: true
env:
    DOWNLOAD_URL: "https://github.com/elecordapp/elecord-desktop/releases/download/v"
    WIN_UPDATE_PATH: "/desktop/update/win32/x64"
    WIN_INSTALL_PATH: "/desktop/install/win32/x64"
    SKIP_REDIRECTS: false
# permissions:
#     contents: write
#     pull-requests: write
jobs:
    redirects:
        name: Update packages.elecord.app
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: Get app version
              run: |
                  version=$(jq -r '.version' package.json)
                  echo "VERSION: $version"
                  echo "VERSION=$version" >> $GITHUB_ENV
                  echo "FULL_DOWNLOAD_URL=${{ env.DOWNLOAD_URL }}$version" >> $GITHUB_ENV

            - name: Update RELEASES file
              # download the RELEASES file from the latest github release
              run: |
                  mkdir -p ./artifacts
                  curl -L "${{ env.FULL_DOWNLOAD_URL }}/RELEASES" -o ./artifacts/RELEASES.txt
                  cp -f ./artifacts/RELEASES.txt ./root${{ env.WIN_UPDATE_PATH }}/RELEASES.txt

            - name: Check existing redirects for current version
              # check if _redirects already contains any refferences to the current version
              run: |
                  if grep -q ${{ env.VERSION }} ./root/_redirects; then
                      echo "Redirects for ${{ env.VERSION }} already exist, skipping new redirects"
                      echo "SKIP_REDIRECTS=true" >> $GITHUB_ENV
                  fi

            - name: Modify versionless redirect
            # replace the first line with the latest version redirect
            run: |
                sed -i "1s#.*#${{ env.WIN_INSTALL_PATH }}/elecord%20Setup.exe \
                ${{ env.FULL_DOWNLOAD_URL }}/elecord.Setup.${{ env.VERSION }}.exe#" \
                ./root/_redirects

            - name: Add installer redirect
              if: env.SKIP_REDIRECTS != 'true'
              run: |
                  echo "${{ env.WIN_INSTALL_PATH }}/elecord%20Setup%20${{ env.VERSION }}.exe \
                  ${{ env.FULL_DOWNLOAD_URL }}/elecord.Setup.${{ env.VERSION }}.exe" >> ./root/_redirects

            - name: Add updater redirect
              if: env.SKIP_REDIRECTS != 'true'
              run: |
                  echo "${{ env.WIN_UPDATE_PATH }}/elecord-desktop-${{ env.VERSION }}-full.nupkg \
                  ${{ env.FULL_DOWNLOAD_URL }}/elecord-desktop-${{ env.VERSION }}-full.nupkg" >> ./root/_redirects

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.ELECORD_DESKTOP_TOKEN }}
                  commit-message: "chore(root): update redirects for ${{ env.VERSION }}"
                  base: master
                  branch: update-redirects
                  title: "Update redirects for ${{ env.VERSION }}"
                  body: |
                      GitHub action update to packages.elecord.app redirects.
                      - https://packages.elecord.app${{ env.WIN_INSTALL_PATH }}/elecord%20Setup.exe
                      - https://packages.elecord.app${{ env.WIN_INSTALL_PATH }}/elecord%20Setup%20${{ env.VERSION }}.exe
                      - https://packages.elecord.app${{ env.WIN_UPDATE_PATH }}/elecord-desktop-${{ env.VERSION }}-full.nupkg
                      - https://packages.elecord.app${{ env.WIN_UPDATE_PATH }}/RELEASES
