# This action uploads the newly built artifacts as a GitHub release.

on:
    workflow_call:
        secrets:
            ELECORD_DESKTOP_TOKEN:
                required: true
# permissions:
#     contents: write
jobs:
    release:
        name: Release
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: Get app version
              run: |
                  version=$(jq -r '.version' package.json)
                  echo "VERSION: $version"
                  echo "VERSION=$version" >> $GITHUB_ENV

            - name: Create artifacts directory
              run: |
                  mkdir -p ./artifacts

            - uses: actions/download-artifact@v4
              with:
                  name: win-x64 # .zip from build_windows workflow
                  path: ./artifacts # downloads and extracts files here

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.ELECORD_DESKTOP_TOKEN }}
                  tag_name: v${{ env.VERSION }}
                  name: v${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  files: |
                      ./artifacts/squirrel-windows/elecord Setup ${{ env.VERSION }}.exe
                      ./artifacts/squirrel-windows/elecord-desktop-${{ env.VERSION }}-full.nupkg
                      ./artifacts/squirrel-windows/RELEASES
                  body: "[See the full elecord changelog](https://github.com/elecordapp/elecord-web/releases/tag/v${{ env.VERSION }})"
